language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
matrix:
  include:
    - node_js: "4.0"
      env: BROWSER=true
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
  # - npm install -g npm@2.6
  # - npm install -g eslint
before_script:
  # - npm install karma-sauce-launcher
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - "[ $BROWSER == false ] || npm run test-karma"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js"
  - codecov -t aac82c03-ba44-441a-868b-0538c35867ed
env:
  global:
  - CODECOV_TOKEN: aac82c03-ba44-441a-868b-0538c35867ed
  # matrix: BROWSER=false
after_success:
- npm run coveralls
- bash <(curl -s https://codecov.io/bash)